### ISSUE TITLE
vnc 7.6.7  arm镜像，socks连接报错

### ISSUE THREAD

**Issue by redjumper** [Hagb/docker-easyconnect#131]
作者你好，使用最新non-amd64分支编译vnc 7.6.7镜像，能正常登录，通过socks连接会报错，看了下/tmp下没有danted.conf
Mar 28 01:41:27 (1648431687.589625) danted[10231]: error: parseconfig(): could not open config file /tmp/danted.conf
Mar 28 01:41:27 (1648431687.589889) danted[10231]: alert: mother[1/1]: shutting down

docker-compose文件如下
```
version: '2.4'

services:
  easyconnect:
    image: xxxx/docker-easyconnect:7.6.7
    container_name: easyconnect
    hostname: easyconnect
    ports:
      - "1080:1080"
      - "5901:5901"
    networks:
      easyconnect_net:
    cap_add:
      - NET_ADMIN
    restart: on-failure:5
    tty: true
    devices:
      - "/dev/net/tun"
    volumes:
      - /data/docker/easyconnect/data:/root

networks:
  easyconnect_net:
    driver: bridge
    ipam:
      driver: default
```

**Comment by Hagb** [comment]
`non-amd64` 分支没有合并对对内存泄露问题和 dante 配置文件位置的修复，请参照 https://github.com/Hagb/docker-easyconnect/issues/128#issuecomment-1078708095 使用 `thread_reuse` 分支

**Comment by redjumper** [comment]
thread_reuse分支是基于手机端的吗。拉取了thread_reuse分支编译，登录时提示The EasyConnect version is not consistent with server version.Please update the client.
```
git clone -b thread_reuse https://github.com/hagb/docker-easyconnect.git
cd docker-easyconnect
git submodule update --init --recursive
docker image build -f Dockerfile.compile -t compile .
EC_VER=7.6.7
docker image build --build-arg EC_URL=$(cat ec_urls/${EC_VER}.txt) --tag xxxx/docker-easyconnect -f Dockerfile .
```

**Comment by Hagb** [comment]
> thread_reuse分支是基于手机端的吗。拉取了thread_reuse分支编译，登录时提示The EasyConnect version is not consistent with server version.Please update the client.
> 
> ```
> git clone -b thread_reuse https://github.com/hagb/docker-easyconnect.git
> cd docker-easyconnect
> git submodule update --init --recursive
> docker image build -f Dockerfile.compile -t compile .
> EC_VER=7.6.7
> docker image build --build-arg EC_URL=$(cat ec_urls/${EC_VER}.txt) --tag xxxx/docker-easyconnect -f Dockerfile .
> ```

不是基于手机端的，是基于 PC 版+qemu-user，差不多是 `non-amd64` 合并进 `develop` 分支的基础上加入了对 qemu 内存泄露问题的 [workaround](https://github.com/Hagb/thread_reuse)。

尝试
1. 启动容器前，清空挂载到容器 `/root` 的目录（在 README 的例子里是 `~/.ecdata`），或者不对容器的 `/root` 目录进行挂载，试试能不能成功登录
2. 如果 1 不凑效，那么在 1 的基础上，在容器的启动参数中加入 `-e QEMU_THREAD_REUSE=''` 关闭 [workaround](https://github.com/Hagb/thread_reuse)，试试能不能成功登录

**Comment by redjumper** [comment]
不挂载/root，并且关闭workaround，还是在输入服务器地址后提示升级客户端
```
Error: ipv4: FIB table does not exist.
Flush terminated
WARNING: obsolete config item on line 7
WARNING: obsolete config item on line 8
WARNING: obsolete config item on line 9
WARNING: obsolete config item on line 10
WARNING: logging deactivated (can't log to stdout when daemonized)
Cleaning stale pidfile '/root/.vnc/easyconnect:5901.pid'!

New Xtigervnc server 'easyconnect:1 (root)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd easyconnect:1 to connect to the VNC server.

(node:76) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

```

**Comment by Hagb** [comment]
尝试 https://github.com/Hagb/docker-easyconnect/issues/88#issuecomment-1075839012 ？

**Comment by redjumper** [comment]
> 尝试 [#88 (comment)](https://github.com/Hagb/docker-easyconnect/issues/88#issuecomment-1075839012) ？
也不行
![ec](https://user-images.githubusercontent.com/16910542/160343562-e41f5406-b971-400f-a94d-f31bc2696426.png)

**Comment by Hagb** [comment]
那真是挺奇怪的… `non-amd64` 和 `thread_reuse` 分支之间的差异 https://github.com/Hagb/docker-easyconnect/compare/non-amd64...thread_reuse 和 EasyConnect 版本并没有太直接的关系…

还有一种可能是 `develop` 引入的另一个粗暴得多的 workaround https://github.com/Hagb/docker-easyconnect/commit/502bccac2f470c7adf8eb94a2cc4fe4244456cec 的干扰，`thread_reuse` 分支启动的输出里有没有出现 `ECAgent spend memory 2xx MB > 256 MB! Kill ECAgent!` 的字样？在启动参数中再加入 `-e QEMU_ECAGENT_MEM_LIMIT=512` 能不能解决问题？

此外请附上完整的启动命令行。

**Comment by redjumper** [comment]
无论开启还是关闭workaround，docker logs都没有看到
`ECAgent spend memory 2xx MB > 256 MB! Kill ECAgent!`
只有满屏的
`(node:77) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
`

docker-compose文件如下
```
version: '2.4'

services:
  easyconnect:
    image: xxxx/docker-easyconnect:7.6.7
    container_name: easyconnect
    hostname: easyconnect
    ports:
      - "1080:1080"
      - "5901:5901"
    networks:
      easyconnect_net:
    cap_add:
      - NET_ADMIN
    environment:
      - PASSWORD=123456
      - QEMU_THREAD_REUSE=''
      - QEMU_ECAGENT_MEM_LIMIT=512
    restart: on-failure:5
    tty: true
    devices:
      - "/dev/net/tun"

networks:
  easyconnect_net:
    driver: bridge
    ipam:
      driver: default
```

**Comment by Hagb** [comment]
如果直接使用 https://github.com/Hagb/docker-easyconnect/issues/88#issuecomment-1075839012 ，需要挂载宿主机的 `~/.ecdata` 到容器的 `/root`。

保险一点的办法是清空 `~/.ecdata` 后启动容器（其中进行了上述挂载），之后 `~/.ecdata` 应该就会出现相应的配置文件了。关掉容器再应用 https://github.com/Hagb/docker-easyconnect/issues/88#issuecomment-1075839012 ，之后再次启动容器

**Comment by redjumper** [comment]
> 如果直接使用 [#88 (comment)](https://github.com/Hagb/docker-easyconnect/issues/88#issuecomment-1075839012) ，需要挂载宿主机的 `~/.ecdata` 到容器的 `/root`。
> 
> 保险一点的办法是清空 `~/.ecdata` 后启动容器（其中进行了上述挂载），之后 `~/.ecdata` 应该就会出现相应的配置文件了。关掉容器再应用 [#88 (comment)](https://github.com/Hagb/docker-easyconnect/issues/88#issuecomment-1075839012) ，之后再次启动容器

昨天是直接容器内修改，然后重启容器

**Comment by Hagb** [comment]
> 昨天是直接容器内修改，然后重启容器
> docker exec -it easyconnect /bin/bash
> sed后重启

我不是很确定 EasyConnect 在退出的时候是否会覆写配置文件

**Comment by redjumper** [comment]
重启后查看过文件，没被覆盖

**Comment by Hagb** [comment]
能提供一下把 workaround 重新开启后运行容器，容器内 `busybox ps` 的输出吗？

此外，`/usr/share/sangfor/EasyConnect/resources/logs` 中的日志有可能有有用的信息。

**Comment by redjumper** [comment]
docker-compose文件如下，并且参照#88修改/root/conf/pkg_version.xml文件
```
version: '2.4'

services:
  easyconnect:
    image: xxxx/docker-easyconnect:7.6.7
    container_name: easyconnect
    hostname: easyconnect
    ports:
      - "1080:1080"
      - "5901:5901"
    networks:
      easyconnect_net:
    cap_add:
      - NET_ADMIN
    environment:
      - PASSWORD=123456
      - QEMU_THREAD_REUSE=''
      - QEMU_ECAGENT_MEM_LIMIT=512
    restart: on-failure:5
    tty: true
    devices:
      - "/dev/net/tun"

networks:
  easyconnect_net:
    driver: bridge
    ipam:
      driver: default

```
> root@easyconnect:~/conf# busybox ps
> PID   USER     COMMAND
>     1 root     {start-sangfor.s} /bin/bash /usr/local/bin/start-sangfor.sh
>    29 root     {start.sh} /bin/bash /usr/local/bin/start.sh
>    31 root     {start.sh} /bin/bash /usr/local/bin/start.sh
>    35 daemon   tinyproxy -c /etc/tinyproxy.conf
>    50 root     {tigervncserver} /usr/bin/perl /usr/bin/tigervncserver :1 -geometry 800x600 -localhost no -passwd /root/.vnc/passwd -xstartup flwm
>    51 root     /usr/bin/Xtigervnc :1 -localhost=0 -desktop easyconnect:1 (root) -rfbport 5901 -PasswordFile /root/.vnc/passwd -SecurityTypes VncAuth,TLSVnc -auth /root
>    52 root     flwm
>    57 root     xclip -selection c
>    60 root     /usr/local/libexec/qemu-hack/EasyMonitor -E LD_PRELOAD=/usr/local/lib/libthread_reuse.so /usr/share/sangfor/EasyConnect/resources/bin/EasyMonitor-origin
>    62 root     {start-sangfor.s} /bin/bash /usr/local/bin/start-sangfor.sh
>    72 root     /usr/local/libexec/qemu-hack/ECAgent -E LD_PRELOAD=/usr/local/lib/libthread_reuse.so /usr/share/sangfor/EasyConnect/resources/bin/ECAgent-origin
>    74 root     {start-sangfor.s} /bin/bash /usr/local/bin/start-sangfor.sh
>    75 root     /usr/share/sangfor/EasyConnect/EasyConnect --enable-transparent-visuals --disable-gpu
>    76 root     tail -n 0 -f /usr/share/sangfor/EasyConnect/resources/logs/ECAgent.log
>    77 root     grep \[Register\]cms client connect failed -m 1
>    80 root     /usr/share/sangfor/EasyConnect/EasyConnect --type=zygote --no-sandbox
>   114 root     /usr/share/sangfor/EasyConnect/EasyConnect --type=renderer --no-sandbox --primordial-pipe-token=A49989C49A824C4CFD80920FA053B9B8 --lang=en-US --app-path
>   133 root     /bin/bash
>   166 root     sleep 15
>   167 root     sleep 5
>   172 root     busybox ps
> 

日志文件在下面，初略看了下，没看出什么来。敏感信息已做处理。
[logs.zip](https://github.com/Hagb/docker-easyconnect/files/8367764/logs.zip)
