### ISSUE TITLE
能登录上但是用不了，日志一直有node的警告

### ISSUE THREAD

**Issue by NewHanly** [Hagb/docker-easyconnect#181]
## 问题描述
尝试使用过Archlinux、Ubuntu、Windows的docker，均出现相同的日志，且无法正常使用

## Docker日志
```
WARNING: logging deactivated (can't log to stdout when daemonized)
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
/usr/bin/xauth:  file /root/.Xauthority does not exist
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.
Use of uninitialized value $proto in socket at /usr/bin/tigervncserver line 357.

New '39619fc98bc2:1 (root)' desktop at :1 on machine 39619fc98bc2

Starting applications specified in flwm
Log file is /root/.vnc/39619fc98bc2:1.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd 39619fc98bc2:1 to connect to the VNC server.

(node:90) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:90) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:90) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:90) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:90) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```
## Docker-compose文件
```
version: '2'
services:
    easyconnect:
        image: hagb/docker-easyconnect:7.6.3 # latest, vncless, 7.6.3, vncless-7.6.3, 7.6.7
        devices:
          - /dev/net/tun
        cap_add:
          - NET_ADMIN
        volumes:
          - ./data:/root
        environment:
          - PASSWORD=1234
        ports:
          - "1080:1080"
          - "5901:5901"
          - "8888:8888"
```
