### ISSUE TITLE
Path selection failed, possibly because network connection error occurs. Please try again later.

### ISSUE THREAD

**Issue by uniform641** [Hagb/docker-easyconnect#184]
在win10中使用7.6.7GUI版本连接，在vnc点击连接后出现`
Choosing the optimal line...`提示，数十秒后出现`Path selection failed, possibly because network connection error occurs. Please try again later.`。该问题可稳定复现，无法成功连接至vpn服务器。使用同版本sslvpn客户端可以成功连接至相同的vpn服务器，无上述错误提示。
-----
windows版本：Windows 10 Pro 21H2
docker engine版本：v20.10.20
运行命令：docker run --device /dev/net/tun --cap-add NET_ADMIN -ti -e PASSWORD=xxxx -v $HOME/.ecdata:/root -p 127.0.0.1:5901:5901 -p 127.0.0.1:1080:1080 hagb/docker-easyconnect:7.6.7

**Comment by Hagb** [comment]
试试在 docker 中用 `busybox wget https://vpn的url` 能不能拉取 vpn 服务器的页面？

**Comment by uniform641** [comment]
# busybox wget https://vpn.xx.cn
Connecting to vpn.xx.cn (xxx.xxx.xxx.xxx:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 40): handshake failure
wget: error getting response: Connection reset by peer
# busybox wget http://vpn.xx.cn
Connecting to vpn.xx.cn (xxx.xxx.xxx.xxx:80)
wget: server returned error: HTTP/1.1 502 Bad Gateway

http可以正常连接，和浏览器的表现一样；https busybox看不了

**Comment by weihanhan** [comment]
重启docker删了.ecdata后又马上能连到服务器, 但用到一半也可能会突然掉线

**Comment by shawnding** [comment]
> 

我遇到同样的问题，一直 `Choosing the optimal line...`，busybox返回也一样

**Comment by doctorgreen4721** [comment]
同样的问题，busybox返回内容一样，系统是win11，Docker基于WSL-2。Hyper-V下是黑屏，连登录界面都不会显示。

**Comment by j7168908jx** [comment]
简单debug发现如果同时win里运行了clash等proxy软件就会导致wsl2里的EasyConnect出现这个问题，只为了能跑通的话建议先关闭任何其他代理试试

**Comment by brucmao** [comment]
发现是容器没有设置dns导致的，进入容器执行下面命令就可以
```
echo "nameserver 223.5.5.5" > /etc/resolv.conf
```

**Comment by brucmao** [comment]
目前我使用cli 能正常登录，修改`vpnaddress` ` username`  `password`  为你自己的

docker-compose.yml
```
version: '3'

services:
  easyconnect:
    container_name: vpn
    image: hagb/docker-easyconnect:cli
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    dns:
      - 223.5.5.5
    ports:
      - "127.0.0.1:1080:1080"
      - "127.0.0.1:8888:8888"
    environment:
      - EC_VER=7.6.3
      - CLI_OPTS=-d vpnaddress -u username -p password

```
