### ISSUE TITLE
docker-compose 运行容器，容器无法访问互联网

### ISSUE THREAD

**Issue by skylens** [Hagb/docker-easyconnect#52]
可以访问互联网

```
docker run --name="vpn" --device /dev/net/tun --cap-add NET_ADMIN -ti -v /opt/easyconnect/easyconn:/root/.easyconn -p 1080:1080 -e EC_VER=7.6.7 hagb/docker-easyconnect:cli
```

不可以访问互联网

```yml
version: '3.3'
services:
  easyconnect:
    image: "hagb/docker-easyconnect:cli"
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/easyconnect/easyconn:/root/.easyconn
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - EC_VER=7.6.7
      - EXIT=1
    ports:
      - "1080:1080"
```
