### ISSUE TITLE
error submitting hardware id

### ISSUE THREAD

**Issue by ererermao** [Hagb/docker-easyconnect#9]
### 背景
有mac地址验证

### 问题
无法登陆

### 配置
```
version: "2"
services:
  easyconnect:
    image: hagb/docker-easyconnect:7.6.7
    restart: unless-stopped
    mac_address: xx:xx:xx:xx:xx:xx
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./.ecdata:/root
    ports:
      - "5901:5901"
      - "1080:1080"
```
