### ISSUE TITLE
podman 运行镜像后socks5 无法使用

### ISSUE THREAD

**Issue by siruoren** [Hagb/docker-easyconnect#98]
podman 运行镜像后socks5 端口可以访问，代理页面打不开，显示连接被重置

**Comment by Hagb** [comment]
请问用的是什么启动参数？

**Comment by siruoren** [comment]
podman-compose.yml内容如下

```
version: '3.8'
services:
    easyconnect:
      image: 'hagb/docker-easyconnect:7.6.7'
      container_name: "easyconnect"
      #restart: unless-stopped
      #privileged: true
      hostname: 'easyconnect'
      environment:
        TZ: 'Asia/Shanghai'
        PASSWORD: 123456
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun
      deploy:
        resources:
          limits:
            memory: 512M
            cpus: '0.5'
      ports:
        - '20080:1080'
        - '25901:5901'
      volumes:
        - ./.ecdata:/root

```
